#!/bin/bash

# Setup GitHub Pages Environment
echo "🔧 Setting up GitHub Pages environment..."

echo "📋 Please follow these steps in your GitHub repository:"
echo ""
echo "1. Go to your repository on GitHub"
echo "2. Navigate to Settings → Pages"
echo "3. Under 'Source', select 'GitHub Actions'"
echo "4. Save the settings"
echo ""
echo "5. Go to Settings → Environments"
echo "6. Click 'New environment'"
echo "7. Name it: github-pages"
echo "8. Click 'Configure environment'"
echo "9. Click 'Save protection rules'"
echo ""
echo "10. Go to Settings → Actions → General"
echo "11. Set 'Actions permissions' to 'Allow all actions'"
echo "12. Set 'Workflow permissions' to 'Read and write permissions'"
echo "13. Check 'Allow GitHub Actions to create and approve pull requests'"
echo ""
echo "✅ After completing these steps, test the deployment:"
echo ""
echo "Option 1 - Manual trigger:"
echo "1. Go to Actions tab"
echo "2. Click 'Deploy Angular Portfolio to GitHub Pages'"
echo "3. Click 'Run workflow' button"
echo "4. Select 'main' branch"
echo "5. Click 'Run workflow'"
echo ""
echo "Option 2 - Push trigger:"
echo "   git add ."
echo "   git commit -m 'Test deployment'"
echo "   git push origin main"
echo ""
echo "🔗 Your portfolio will be available at:"
echo "   https://ahmedkhalil777.github.io/AhmedKhalil777/"
echo ""
echo "📊 Monitor the deployment in your repository's Actions tab"
