#!/bin/bash

# Test hash routing fix
echo "🧪 Testing Angular hash routing fix..."

echo "📋 After deployment, test these URLs:"
echo ""
echo "1. Main page:"
echo "   https://ahmedkhalil777.github.io/AhmedKhalil777/"
echo ""
echo "2. Resume page (with hash):"
echo "   https://ahmedkhalil777.github.io/AhmedKhalil777/#/resume"
echo ""
echo "3. Test navigation:"
echo "   - Navigate from home to resume"
echo "   - Refresh the page - should stay on resume"
echo "   - Try direct URL access with hash"
echo ""
echo "✅ Expected results:"
echo "   - URLs will have hash (#/resume instead of /resume)"
echo "   - Direct URL access should work"
echo "   - Page refresh should stay on correct page"
echo "   - Navigation should work smoothly"
echo "   - No 404 errors for valid routes"
echo ""
echo "🔍 If routing still doesn't work:"
echo "1. Check that withHashLocation() is configured in main.ts"
echo "2. Verify 404.html is deployed"
echo "3. Check browser console for errors"
echo ""
echo "📊 Monitor deployment in Actions tab"
echo "🌐 Your portfolio will be at: https://ahmedkhalil777.github.io/AhmedKhalil777/"
